// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diieheagpzlqatqpzjua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpaWVoZWFncHpscWF0cXB6anVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjYxNjAsImV4cCI6MjA2MjEwMjE2MH0._kaKTqG0RIs3DZCQ9GxYNSpdBS9P78L8O_RZOzwKwbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);